-- deletes all quizzes (and respective answers) generated by demo-student

with aux as (
	select id
	from quiz_answers 
	where quiz_id in (select id from quizzes where type = 'GENERATED')
	and user_id = 676
)
delete from question_answers where quiz_answer_id in (select id from aux);

with aux as (
	select id
	from quiz_answers 
	where quiz_id in (select id from quizzes where type = 'GENERATED')
	and user_id = 676
)
delete from quiz_answers where id in (select id from aux);

delete from quiz_questions where quiz_id in (select id from quizzes where type = 'GENERATED');

delete from quizzes where type = 'GENERATED';
